'use strict';

// tests for cognitoPreSignup
// Generated by serverless-jest-plugin

const auth = require('../src/auth');
const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrappedCustomMessage = lambdaWrapper.wrap(auth, { handler: 'customMessage' });
const event = {
  request: {
  },
  triggerSource: 'CustomMessage_SignUp',
  response: {}
}

describe('cognitoPreSignup', () => {
  beforeAll((done) => {
    done();
  });

  it('cognitoPreSignup succesful operation', async () => {
    let { response } = await wrappedCustomMessage.run(event);
    expect(response.emailSubject).not.toBeUndefined();
    event.triggerSource = 'CustomMessage_AdminCreateUser';
    event.response = {}; 
    ({ response } = await wrappedCustomMessage.run(event));
    expect(response.emailSubject).not.toBeUndefined();
    event.triggerSource = 'CustomMessage_';
    event.response = {};
    ({ response } = await wrappedCustomMessage.run(event));
    expect(response.emailSubject).toBeUndefined();
  });
});
