'use strict';

// tests for healthCheck
// Generated by serverless-jest-plugin

const mod = require('../src/status');
const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'healthCheck' });

describe('healthCheck', () => {
  beforeAll((done) => {
    done();
  });

  it('get status, expect 200 ACTIVE', () => {
    return wrapped.run({}).then((response) => {
      expect(response.statusCode).toBe(200);
      expect(response.body).toBe("\"ACTIVE\"");
    });
  });

  it('get status for non existing table, expect 500', () => {
    process.env.consumerAuthTableName = 'test';
    return wrapped.run({}).then((response) => {
      expect(response.statusCode).toBe(500);
    });
  });
});
