'use strict';

// tests for cognitoPreSignup
// Generated by serverless-jest-plugin

const auth = require('../src/auth');
const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrappedCustomMessage = lambdaWrapper.wrap(auth, { handler: 'postAuthentication' });

const event = {
    version: '1',
    region: 'us-east-1',
    userPoolId: 'us-east-1_j0IcMHZI1',
    userName: 'bdb2f56c-42f9-46be-a9ed-0453884ded17',
    callerContext: {
        awsSdkVersion: 'aws-sdk-unknown-unknown',
        clientId: '1bso3m2dgo7mde8v1arjho3m33'
    },
    triggerSource: 'PostAuthentication_Authentication',
    request: {
        userAttributes: {
            sub: 'bdb2f56c-42f9-46be-a9ed-0453884ded17',
            email_verified: 'true',
            'cognito:user_status': 'CONFIRMED',
            'cognito:email_alias': 'admin-roundco@stoketalent.com',
            profile: 'Rounding Numbers Co',
            given_name: 'RoundCo',
            family_name: 'Admin',
            email: 'admin-roundco@stoketalent.com',
            accountType: 'freemium'
        },
        newDeviceUsed: false
    },
    response: {}
}

describe('postAuthentication', () => {
    beforeAll((done) => {
        done();
    });

    it('postAuthentication succesful operation', async () => {
        let { response } = await wrappedCustomMessage.run(event);
        expect(response).toBeDefined();
    });
});
